//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public string ArtCod { get; set; }
        public string ArtNom { get; set; }
        public string ArtTipo { get; set; }
        public int ArtTam { get; set; }
        public System.DateTime ArtFechVen { get; set; }
        public Nullable<decimal> ArtPre { get; set; }
        public string ArtCatCod { get; set; }
        public bool ArtActivo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
