//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public string CatCod { get; set; }
        public string CatNom { get; set; }
        public bool CatActivo { get; set; }
    }
}
