//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string CliCI { get; set; }
        public string CliNom { get; set; }
        public string CliNumTar { get; set; }
        public string CliTel { get; set; }
    }
}
