//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int VenNum { get; set; }
        public System.DateTime VenFec { get; set; }
        public decimal VenMon { get; set; }
        public string VenDir { get; set; }
        public string VenCliCI { get; set; }
        public string VenEmpUsu { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
